// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BionicReading
{
    internal sealed partial class Vsix
    {
        public const string Id = "BionicReading.5fc630d9-8214-4730-b3e7-60d50c1eaa1b";
        public const string Name = "Bionic Reading";
        public const string Description = @"Bionic Reading uses bold text to on the first part of words, which makes the brain complete the rest more easily. This makes it easier for some people to read text and code";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
