// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EmphasizeWords
{
    internal sealed partial class Vsix
    {
        public const string Id = "EmphasizeWords.5fc630d9-8214-4730-b3e7-60d50c1eaa1b";
        public const string Name = "Emphasize Words";
        public const string Description = @"Emphasize Words uses bold text on the first part of words, which makes the brain complete the rest more easily. This makes it easier for some people to read text and code";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
